meta:
    script: python main_wait.py
    mode: grid 
    sample: 20
    repeat: 1
    prefix: demo_wait
    gpus: 1
    key: ['wait']
    
hp: 
    wait: [5, 10, 20, 100, 300]

sbatch:
    exclude: deep[1-9]
     
